server:
  port: 8181
  servlet:
    context-path: /

spring:
  application:
    name: chess.srv
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
#    mode: HTML5
#    suffix: .html
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
    #这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    prefix: classpath:/templates/
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://47.101.71.10:3306/CHIK?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true
    username: root
    password: ct584521
    driver-class-name: com.mysql.cj.jdbc.Driver
  #############################################
  ## 以下为缓存相关                           ##
  #############################################
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
    serialization.write_dates_as_timestamps: false
    default-property-inclusion: non_null
  redis:
    host: 192.168.8.130
    port: 36379
    password: jzy@2019
    timeout: 60000
    database: 15
    lettuce:
      pool:
        max-active: 8
        max-wait: -1s
        max-idle: 8
        min-idle: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: 192.168.8.130
    port: 5672
    username: guest
    password: guest


logging:
#  kafka:
#    topic: log_topic
#    servers: ${info.kafkaUrl}
#  config: classpath:logback-kafka.xml
  level:
    com.example: debug
