server:
  port: 8181
  servlet:
    context-path: /

spring:
  application:
    name: chess.srv
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
#    mode: HTML5
#    suffix: .html
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
    #这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    prefix: classpath:/templates/
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://47.101.71.10:3306/CHIK?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true
    username: root
    password: ct584521
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
#  kafka:
#    topic: log_topic
#    servers: ${info.kafkaUrl}
#  config: classpath:logback-kafka.xml
  level:
    com.example: debug
